from __future__ import annotations

from typing import Any, Protocol, Sequence

import numpy as np

from embodied_agent.simulator import SceneConfig
from embodied_agent.types import Vec3, WorldState


class PickPlaceSimulationProtocol(Protocol):
    config: SceneConfig
    object_names: tuple[str, ...]
    zone_names: tuple[str, ...]
    object_ids: dict[str, Any]
    zone_ids: dict[str, Any]
    zone_positions: dict[str, Vec3]
    held_object_name: str | None

    def reset(self) -> None: ...
    def fast_reset(self) -> None: ...
    def reset_task(
        self,
        object_xy: tuple[float, float] | None = None,
        zone_xy: tuple[float, float] | None = None,
        holding_object: bool = False,
        object_layout: dict[str, tuple[float, float]] | None = None,
        zone_layout: dict[str, tuple[float, float]] | None = None,
        held_object_name: str | None = None,
    ) -> None: ...
    def default_object_layout(self) -> dict[str, tuple[float, float]]: ...
    def default_zone_layout(self) -> dict[str, tuple[float, float]]: ...
    def sample_scene_layout(
        self,
        rng: Any = None,
        object_names: Sequence[str] | None = None,
        zone_names: Sequence[str] | None = None,
        min_separation: float = 0.12,
        object_x_range: tuple[float, float] | None = None,
        object_y_range: tuple[float, float] | None = None,
        zone_x_range: tuple[float, float] | None = None,
        zone_y_range: tuple[float, float] | None = None,
        object_candidates: Sequence[tuple[float, float]] | None = None,
        zone_candidates: Sequence[tuple[float, float]] | None = None,
    ) -> tuple[dict[str, tuple[float, float]], dict[str, tuple[float, float]]]: ...
    def observe_scene(self, instruction: str = "") -> WorldState: ...
    def get_object_position(self, object_name: str) -> Vec3: ...
    def get_object_pose(self, object_name: str) -> tuple[Vec3, tuple[float, float, float, float]]: ...
    def get_quaternion_from_euler(self, euler: tuple[float, float, float]) -> tuple[float, float, float, float]: ...
    def get_skill_observation(self, object_name: str, zone_name: str) -> np.ndarray: ...
    def get_skill_metrics(self, object_name: str, zone_name: str) -> dict[str, float]: ...
    def capture_skill_state(self, object_name: str, zone_name: str) -> dict[str, object]: ...
    def restore_runtime_state(self, state: dict[str, Any], object_name: str, zone_name: str) -> None: ...
    def simulate_steps(self, steps: int) -> None: ...
    def apply_skill_action(
        self,
        delta_position: Vec3,
        gripper_command: float,
        action_steps: int = 24,
        object_name: str = "red_block",
    ) -> WorldState: ...
    def pick_object(self, object_name: str) -> None: ...
    def place_object(self, zone_name: str) -> None: ...
    def is_object_held(self, object_name: str) -> bool: ...
    def is_pick_success(self, object_name: str) -> bool: ...
    def is_object_in_zone(self, object_name: str, zone_name: str, tolerance: float = 0.08) -> bool: ...
    def is_place_success(self, object_name: str, zone_name: str, tolerance: float = 0.08) -> bool: ...
    def move_end_effector(self, target_position: Vec3, steps: int = 240) -> None: ...
    def teleport_end_effector(self, target_position: Vec3) -> None: ...
    def teleport_end_effector_pose(
        self,
        target_position: Vec3,
        target_orientation: tuple[float, float, float, float],
    ) -> None: ...
    def open_gripper(self) -> None: ...
    def close_gripper(self) -> None: ...
    def get_end_effector_pose(self) -> tuple[Vec3, tuple[float, float, float, float]]: ...
    def shutdown(self) -> None: ...
